### ISSUE TITLE
Some code missed in the final_dissertation.

### ISSUE THREAD

**Issue by zrg1993** [massimo-rizzoli/BNSL#1]
Thanks for your share of dissertation and code. The dissertation is very easy to read. But I find some codes are not displayed in page 31 and 33.  Would you like to share the two lines of unseen codes ?

**Comment by massimo-rizzoli** [comment]
Thank you for pointing it out, I did not notice that the code was clipped out of the page.
If you are interested in the code you should look at the repository. The final dissertation is from 2021, but the code has been improved and updated in the repository, since we have [an extention](https://arxiv.org/abs/2204.03526) of this work. You can find all the code in the [bnslqa folder](https://github.com/massimo-rizzoli/BNSL-QA-python/tree/master/bnslqa).
For the specific functions that were clipped in the dissertation, you can find them here:
- Page 31:
    - [calcSi](https://github.com/massimo-rizzoli/BNSL-QA-python/blob/15e5284fe3ce08a699cf8235584d07f55a143147/bnslqa/solvers/qubo_values.py#L128)

- Page 33:
    - [calcDeltaConsist](https://github.com/massimo-rizzoli/BNSL-QA-python/blob/15e5284fe3ce08a699cf8235584d07f55a143147/bnslqa/solvers/qubo_values.py#L222)
    - [calcQUBOMatrix](https://github.com/massimo-rizzoli/BNSL-QA-python/blob/15e5284fe3ce08a699cf8235584d07f55a143147/bnslqa/solvers/qubo_matrix.py#L43)

- Page 35
    - [addHtrans](https://github.com/massimo-rizzoli/BNSL-QA-python/blob/15e5284fe3ce08a699cf8235584d07f55a143147/bnslqa/solvers/qubo_matrix.py#L121)

**Comment by zrg1993** [comment]
Thank you very much ! I will check the updated code.
